GET http://localhost:4000/users


###


POST http://localhost:4000/users/signup
content-type: application/json

{
    "username": "sample",
    "email": "something@hotmail.com",
    "password": "abcdef"
}


###


GET http://localhost:4000/snippetr


###


POST http://localhost:4000/snippetr/create
content-type: application/json

{
    "title": "some title",
    "story": "a very long story",
    "image": "abcdef"
}


###


